<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HeritageSite;
use Illuminate\Support\Str;

class HeritageSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'site_category_id' => 1,
                'name' => 'Candi Prambanan',
                'slug' => Str::slug('Candi Prambanan'),
                'description' => 'Kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9.',
                'address' => 'Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Prambanan, Sleman',
                'latitude' => -7.7520206,
                'longitude' => 110.4892787,
                'operating_hours' => json_encode(['Senin-Minggu' => '06:00-17:00']),
                'admission_fee' => 50000,
                'registration_number' => 'CB.01.01',
                'designation_year' => '1991',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => 'Keraton Yogyakarta',
                'slug' => Str::slug('Keraton Yogyakarta'),
                'description' => 'Istana resmi Kesultanan Ngayogyakarta Hadiningrat yang kini berlokasi di Kota Yogyakarta.',
                'address' => 'Jl. Rotowijayan Blok No. 1, Panembahan, Kraton, Kota Yogyakarta',
                'latitude' => -7.8052845,
                'longitude' => 110.3642031,
                'operating_hours' => json_encode(['Senin-Minggu' => '08:00-14:00']),
                'admission_fee' => 15000,
                'registration_number' => 'CB.02.01',
                'designation_year' => '1995',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 3,
                'name' => 'Masjid Gedhe Kauman',
                'slug' => Str::slug('Masjid Gedhe Kauman'),
                'description' => 'Masjid raya Kesultanan Yogyakarta, dibangun pada masa Sri Sultan Hamengku Buwono I.',
                'address' => 'Alun-Alun Keraton, Jl. Kauman, Ngupasan, Gondomanan, Kota Yogyakarta',
                'latitude' => -7.8038880,
                'longitude' => 110.3622220,
                'operating_hours' => json_encode(['Senin-Minggu' => '24 Jam']),
                'admission_fee' => 0,
                'registration_number' => 'CB.03.01',
                'designation_year' => '2000',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => 'Candi Borobudur',
                'slug' => Str::slug('Candi Borobudur'),
                'description' => 'Candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.',
                'address' => 'Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Magelang',
                'latitude' => -7.6078738,
                'longitude' => 110.2037513,
                'operating_hours' => json_encode(['Senin-Minggu' => '06:30-16:30']),
                'admission_fee' => 50000,
                'registration_number' => 'CB.01.02',
                'designation_year' => '1991',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => 'Candi Ratu Boko',
                'slug' => Str::slug('Candi Ratu Boko'),
                'description' => 'Situs purbakala yang merupakan sisa keraton masa lampau, terletak di selatan Prambanan.',
                'address' => 'Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Prambanan, Sleman',
                'latitude' => -7.7705416,
                'longitude' => 110.4894158,
                'operating_hours' => json_encode(['Senin-Minggu' => '06:00-17:00']),
                'admission_fee' => 40000,
                'registration_number' => 'CB.01.03',
                'designation_year' => '1998',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => 'Taman Sari',
                'slug' => Str::slug('Taman Sari'),
                'description' => 'Situs bekas taman atau kebun istana Keraton Ngayogyakarta Hadiningrat.',
                'address' => 'Patehan, Kraton, Kota Yogyakarta',
                'latitude' => -7.8099307,
                'longitude' => 110.3590059,
                'operating_hours' => json_encode(['Senin-Minggu' => '09:00-15:00']),
                'admission_fee' => 15000,
                'registration_number' => 'CB.02.02',
                'designation_year' => '1995',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 3,
                'name' => 'Masjid Mataram Kotagede',
                'slug' => Str::slug('Masjid Mataram Kotagede'),
                'description' => 'Masjid tertua di Yogyakarta yang dibangun peninggalan Kerajaan Mataram Islam.',
                'address' => 'Jl. Masjid Besar Mataram, Sayangan, Jagalan, Banguntapan, Bantul',
                'latitude' => -7.8284589,
                'longitude' => 110.3957262,
                'operating_hours' => json_encode(['Senin-Minggu' => '24 Jam']),
                'admission_fee' => 0,
                'registration_number' => 'CB.03.02',
                'designation_year' => '2005',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => 'Candi Mendut',
                'slug' => Str::slug('Candi Mendut'),
                'description' => 'Candi Buddha yang letaknya berdekatan dengan Candi Borobudur.',
                'address' => 'Jl. Mayor Kusen, Sumberrejo, Mendut, Mungkid, Magelang',
                'latitude' => -7.6046200,
                'longitude' => 110.2297120,
                'operating_hours' => json_encode(['Senin-Minggu' => '07:00-17:00']),
                'admission_fee' => 10000,
                'registration_number' => 'CB.01.04',
                'designation_year' => '2002',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => 'Pura Mangkunegaran',
                'slug' => Str::slug('Pura Mangkunegaran'),
                'description' => 'Istana resmi Kadipaten Mangkunegaran di Surakarta yang dibangun tahun 1757.',
                'address' => 'Jl. Ronggowarsito No.83, Keprabon, Banjarsari, Kota Surakarta',
                'latitude' => -7.5665809,
                'longitude' => 110.8229871,
                'operating_hours' => json_encode(['Senin-Minggu' => '08:00-15:00']),
                'admission_fee' => 20000,
                'registration_number' => 'CB.02.03',
                'designation_year' => '2010',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => 'Candi Plaosan',
                'slug' => Str::slug('Candi Plaosan'),
                'description' => 'Candi Buddha yang dibangun oleh Rakai Pikatan untuk permaisurinya, Pramodhawardhani.',
                'address' => 'Jl. Candi Plaosan, Plaosan Lor, Bugisan, Prambanan, Klaten',
                'latitude' => -7.7408719,
                'longitude' => 110.5042617,
                'operating_hours' => json_encode(['Senin-Minggu' => '08:00-16:00']),
                'admission_fee' => 10000,
                'registration_number' => 'CB.01.05',
                'designation_year' => '2008',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        HeritageSite::insert($sites);
    }
}
