<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HeritageSite;
use Illuminate\Support\Str;

class HeritageSiteSeeder extends Seeder
{
    public function run(): void
    {
        $sites = [
            [
                'site_category_id' => 1,
                'name' => ['id' => 'Candi Prambanan', 'en' => 'Temple Prambanan'],
                'slug' => Str::slug('Candi Prambanan'),
                'description' => ['id' => 'Kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9.', 'en' => 'Kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9.'],
                'address' => ['id' => 'Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Prambanan, Sleman', 'en' => 'Jl. Raya Solo - Yogyakarta No.16, Kranggan, Bokoharjo, Prambanan, Sleman'],
                'latitude' => -7.7520206,
                'longitude' => 110.4892787,
                'operating_hours' => ['Senin-Minggu' => '06:00-17:00'],
                'registration_number' => 'CB.01.01',
                'designation_year' => '1991',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => ['id' => 'Keraton Yogyakarta', 'en' => 'Palace Yogyakarta'],
                'slug' => Str::slug('Keraton Yogyakarta'),
                'description' => ['id' => 'Istana resmi Kesultanan Ngayogyakarta Hadiningrat yang kini berlokasi di Kota Yogyakarta.', 'en' => 'Istana resmi Kesultanan Ngayogyakarta Hadiningrat yang kini berlokasi di Kota Yogyakarta.'],
                'address' => ['id' => 'Jl. Rotowijayan Blok No. 1, Panembahan, Kraton, Kota Yogyakarta', 'en' => 'Jl. Rotowijayan Blok No. 1, Panembahan, Kraton, Kota Yogyakarta'],
                'latitude' => -7.8052845,
                'longitude' => 110.3642031,
                'operating_hours' => ['Senin-Minggu' => '08:00-14:00'],
                'registration_number' => 'CB.02.01',
                'designation_year' => '1995',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 3,
                'name' => ['id' => 'Masjid Gedhe Kauman', 'en' => 'Grand Mosque Kauman'],
                'slug' => Str::slug('Masjid Gedhe Kauman'),
                'description' => ['id' => 'Masjid raya Kesultanan Yogyakarta, dibangun pada masa Sri Sultan Hamengku Buwono I.', 'en' => 'Masjid raya Kesultanan Yogyakarta, dibangun pada masa Sri Sultan Hamengku Buwono I.'],
                'address' => ['id' => 'Alun-Alun Keraton, Jl. Kauman, Ngupasan, Gondomanan, Kota Yogyakarta', 'en' => 'Alun-Alun Keraton, Jl. Kauman, Ngupasan, Gondomanan, Kota Yogyakarta'],
                'latitude' => -7.8038880,
                'longitude' => 110.3622220,
                'operating_hours' => ['Senin-Minggu' => '24 Jam'],
                'registration_number' => 'CB.03.01',
                'designation_year' => '2000',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => ['id' => 'Candi Borobudur', 'en' => 'Temple Borobudur'],
                'slug' => Str::slug('Candi Borobudur'),
                'description' => ['id' => 'Candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.', 'en' => 'Candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah.'],
                'address' => ['id' => 'Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Magelang', 'en' => 'Jl. Badrawati, Kw. Candi Borobudur, Borobudur, Magelang'],
                'latitude' => -7.6078738,
                'longitude' => 110.2037513,
                'operating_hours' => ['Senin-Minggu' => '06:30-16:30'],
                'registration_number' => 'CB.01.02',
                'designation_year' => '1991',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => ['id' => 'Candi Ratu Boko', 'en' => 'Temple Ratu Boko'],
                'slug' => Str::slug('Candi Ratu Boko'),
                'description' => ['id' => 'Situs purbakala yang merupakan sisa keraton masa lampau, terletak di selatan Prambanan.', 'en' => 'Situs purbakala yang merupakan sisa keraton masa lampau, terletak di selatan Prambanan.'],
                'address' => ['id' => 'Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Prambanan, Sleman', 'en' => 'Jl. Raya Piyungan - Prambanan No.2, Gatak, Bokoharjo, Prambanan, Sleman'],
                'latitude' => -7.7705416,
                'longitude' => 110.4894158,
                'operating_hours' => ['Senin-Minggu' => '06:00-17:00'],
                'registration_number' => 'CB.01.03',
                'designation_year' => '1998',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => ['id' => 'Taman Sari', 'en' => 'Taman Sari'],
                'slug' => Str::slug('Taman Sari'),
                'description' => ['id' => 'Situs bekas taman atau kebun istana Keraton Ngayogyakarta Hadiningrat.', 'en' => 'Situs bekas taman atau kebun istana Keraton Ngayogyakarta Hadiningrat.'],
                'address' => ['id' => 'Patehan, Kraton, Kota Yogyakarta', 'en' => 'Patehan, Kraton, Kota Yogyakarta'],
                'latitude' => -7.8099307,
                'longitude' => 110.3590059,
                'operating_hours' => ['Senin-Minggu' => '09:00-15:00'],
                'registration_number' => 'CB.02.02',
                'designation_year' => '1995',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 3,
                'name' => ['id' => 'Masjid Mataram Kotagede', 'en' => 'Mosque Mataram Kotagede'],
                'slug' => Str::slug('Masjid Mataram Kotagede'),
                'description' => ['id' => 'Masjid tertua di Yogyakarta yang dibangun peninggalan Kerajaan Mataram Islam.', 'en' => 'Masjid tertua di Yogyakarta yang dibangun peninggalan Kerajaan Mataram Islam.'],
                'address' => ['id' => 'Jl. Masjid Besar Mataram, Sayangan, Jagalan, Banguntapan, Bantul', 'en' => 'Jl. Masjid Besar Mataram, Sayangan, Jagalan, Banguntapan, Bantul'],
                'latitude' => -7.8284589,
                'longitude' => 110.3957262,
                'operating_hours' => ['Senin-Minggu' => '24 Jam'],
                'registration_number' => 'CB.03.02',
                'designation_year' => '2005',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => ['id' => 'Candi Mendut', 'en' => 'Temple Mendut'],
                'slug' => Str::slug('Candi Mendut'),
                'description' => ['id' => 'Candi Buddha yang letaknya berdekatan dengan Candi Borobudur.', 'en' => 'Candi Buddha yang letaknya berdekatan dengan Candi Borobudur.'],
                'address' => ['id' => 'Jl. Mayor Kusen, Sumberrejo, Mendut, Mungkid, Magelang', 'en' => 'Jl. Mayor Kusen, Sumberrejo, Mendut, Mungkid, Magelang'],
                'latitude' => -7.6046200,
                'longitude' => 110.2297120,
                'operating_hours' => ['Senin-Minggu' => '07:00-17:00'],
                'registration_number' => 'CB.01.04',
                'designation_year' => '2002',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 2,
                'name' => ['id' => 'Pura Mangkunegaran', 'en' => 'Pura Mangkunegaran'],
                'slug' => Str::slug('Pura Mangkunegaran'),
                'description' => ['id' => 'Istana resmi Kadipaten Mangkunegaran di Surakarta yang dibangun tahun 1757.', 'en' => 'Istana resmi Kadipaten Mangkunegaran di Surakarta yang dibangun tahun 1757.'],
                'address' => ['id' => 'Jl. Ronggowarsito No.83, Keprabon, Banjarsari, Kota Surakarta', 'en' => 'Jl. Ronggowarsito No.83, Keprabon, Banjarsari, Kota Surakarta'],
                'latitude' => -7.5665809,
                'longitude' => 110.8229871,
                'operating_hours' => ['Senin-Minggu' => '08:00-15:00'],
                'registration_number' => 'CB.02.03',
                'designation_year' => '2010',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'site_category_id' => 1,
                'name' => ['id' => 'Candi Plaosan', 'en' => 'Temple Plaosan'],
                'slug' => Str::slug('Candi Plaosan'),
                'description' => ['id' => 'Candi Buddha yang dibangun oleh Rakai Pikatan untuk permaisurinya, Pramodhawardhani.', 'en' => 'Candi Buddha yang dibangun oleh Rakai Pikatan untuk permaisurinya, Pramodhawardhani.'],
                'address' => ['id' => 'Jl. Candi Plaosan, Plaosan Lor, Bugisan, Prambanan, Klaten', 'en' => 'Jl. Candi Plaosan, Plaosan Lor, Bugisan, Prambanan, Klaten'],
                'latitude' => -7.7408719,
                'longitude' => 110.5042617,
                'operating_hours' => ['Senin-Minggu' => '08:00-16:00'],
                'registration_number' => 'CB.01.05',
                'designation_year' => '2008',
                'status' => 'active',
                'is_facility_available' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($sites as $site) {
            HeritageSite::updateOrCreate(
                ['slug' => $site['slug']],
                $site
            );
        }
    }
}
